version: '2.1'
services:
  mysqldb:
    image: mysql:latest
    mem_limit: 1073741824
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-hmysqldb", "-uroot", "-ppassword", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "3306:3306/tcp"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: spring
  nginx:
    build:
      context: ./nginx/
    image: custom/nginx:latest
    ports:
      - "80:80/tcp"
  spring-boot-1:
    image: spring-boot:0.0.1-SNAPSHOT
    depends_on:
      - mysqldb
