server:
  port: 8899
  contextPath: /
#  session:
#    timeout: 60

spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
#    url: jdbc:mysql://localhost:3306/spring
    url: jdbc:mysql://1.230.35.113:3306/spring?characterEncoding=utf8&useUnicode=true&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: "password"
    driver-class-name: com.mysql.jdbc.Driver

  social:
    facebook:
      app-id: 168725713662603
      app-secret: fdf1fee004df10cd3a00adb949e16e5a
    google:
      app-id: 150010817728-rgpsba3l8eu1jqersfmoihaj56jeqpia.apps.googleusercontent.com
      app-secret: suiek6bK3Ni4HfrIMWSCX9Eb
    kakao:
      app-id: 5d657efdb44563718081262c440e74e1
    naver:
      app-id: n0hdLZkE4kNTYFoiXUOJ
      app-secret: qbuxIcZQs6
